
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27018"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_ROOT_PASSWORD}
    command: mongod --port 27018
    restart: always
    healthcheck:
      test: |
        mongosh --port 27018 -u ${MONGO_DB_ROOT_USERNAME} -p ${MONGO_DB_ROOT_PASSWORD} --authenticationDatabase admin --eval 'db.getSiblingDB("admin").runCommand({ping: 1})'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://${MONGO_DB_ROOT_USERNAME}:${MONGO_DB_ROOT_PASSWORD}@mongo:27018/
      - PORT=8080
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27018
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_DB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_DB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_DB_ROOT_USERNAME}:${MONGO_DB_ROOT_PASSWORD}@mongo:27018/
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    restart: always
    depends_on:
      - mongo

  swagger-ui:
    image: nginx:latest
    container_name: swagger-ui
    ports:
      - "8082:80"
    volumes:
      - ./api/swagger-ui:/usr/share/nginx/html
      - ./api/openapi.yaml:/usr/share/nginx/html/openapi.yaml
      - ./api/swagger-ui/nginx.conf:/etc/nginx/conf.d/default.conf
    command: nginx -g 'daemon off;'
    restart: always

volumes:
  mongo-data:
