name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/admin/BridgeMe-Back
            git pull origin main
            if [ $? -ne 0 ]; then
              echo "Error: git pull failed. Aborting deployment."
              exit 1
            fi
            docker compose up -d --build

            echo "Waiting 10 seconds for containers to stabilize..."
            sleep 10

            # Check container status
            CONTAINERS=("mongo" "swagger-ui" "mongo-express" "backend")
            ALL_RUNNING=true

            for CONTAINER_NAME in "${CONTAINERS[@]}"; do
              STATUS=$(docker ps -a --filter "name=${CONTAINER_NAME}" --format "{{.Status}}")
              if [[ "$STATUS" != *"Up"* ]]; then
                echo "Error: Container ${CONTAINER_NAME} is not running. Status: ${STATUS}"
                ALL_RUNNING=false
              else
                echo "Container ${CONTAINER_NAME} is running."
              fi
            done

            if [ "$ALL_RUNNING" = false ]; then
              echo "One or more containers failed to start. Deployment failed."
              exit 1 # Fail the GitHub Actions job
            else
              echo "All specified containers are running. Deployment successful."
            fi
