name: CD

on:
  workflow_dispatch: # これに変更

jobs:
  deploy:
    # needs: ci_test # これは削除
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

    - name: Transfer files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        source: "."
        target: "/home/admin/BridgeMe-Back"
        strip_components: 1 # リポジトリのルートディレクトリをターゲットディレクトリにコピー

    - name: Build and Run Docker Compose on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script:
          - cd /home/admin/BridgeMe-Back
          - docker compose build
          - docker compose up -d
