name: Go CI

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      actions: write # ここを追加
    services:
      mongo:
        image: mongo:latest
        ports:
          - "27018:27018"
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_DB_ROOT_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_DB_ROOT_PASSWORD }}
        options: >- # Healthcheck options
          --health-cmd "mongosh --port 27018 -u ${{ secrets.MONGO_DB_ROOT_USERNAME }} -p ${{ secrets.MONGO_DB_ROOT_PASSWORD }} --authenticationDatabase admin --eval 'db.getSiblingDB(\"admin\").runCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v4


    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: |
        go mod tidy
        go mod vendor

    - name: Auto-commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "ci: Automate go mod tidy and vendor"
        file_pattern: go.mod go.sum vendor/

    - name: Run tests
      run: go test -v ./...