name: Notion Sync

on:
  workflow_dispatch:
  issues:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      - assigned
      - unassigned
      - milestoned
      - demilestoned
      - reopened
      - closed

permissions:
  contents: read
  issues: read

jobs:
  notion_job:
    name: Add GitHub Issues to Notion
    runs-on: ubuntu-latest

    concurrency:
      group: notion-sync-${{ github.event.issue.number || 'manual' }}
      cancel-in-progress: false

    steps:
      - name: (optional) Print event payload (debug)
        if: ${{ runner.debug == '1' }}
        run: |
          echo "event_name=$GITHUB_EVENT_NAME"
          jq . "$GITHUB_EVENT_PATH" || true

      - name: Add GitHub Issues to Notion
        uses: tryfabric/notion-github-action@v1
        with:
          notion-token: ${{ secrets.NOTION_TOKEN }}
          notion-db: ${{ secrets.NOTION_DATABASE }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
